stages:
  - build
  - upload

build_job:
  stage: build
  image: "debian:bullseye"
  before_script:
    - apt-get -y -qq update
    - apt-get -y -qq install eatmydata
    - eatmydata apt-get -y -qq install build-essential cargo tree rustc libstd-rust-dev-wasm32 libssl-dev pkg-config tree zopfli
  script: make install
  cache:
    key: faustctf-merklechat
    paths:
      - .cargo
      - server/target/
      - wasm/target/
      - wasm/target/wasm32-unknown-unknown/release/deps
  artifacts:
    paths:
      - metadata.yml
      - dist_root/
  only:
    - master
  tags:
    - faust
    - docker

upload_job:
  stage: upload
  script:
    - ssh ci-upload@www.faust.cs.fau.de mkdir -p "/var/www/files/internal/ci/faustctf/2021/$CI_PROJECT_NAME"
    - tar -v -czp -H posix -f dist_root.tar.gz -C dist_root .
    - scp metadata.yml dist_root.tar.gz "ci-upload@www.faust.cs.fau.de:/var/www/files/internal/ci/faustctf/2021/$CI_PROJECT_NAME/"
  after_script:
    - find "$CI_PROJECT_DIR" -mindepth 1 -delete
  variables:
    GIT_STRATEGY: none
  only:
    - master
  tags:
    - faust
    - www-upload
